service: serverless-demo

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  #stage: dev # Set the default stage used. Default is dev
  #profile: production # The default profile to use with this service
  #memorySize: 512 # Overwrite the default memory size. Default is 1024
  #deploymentBucket:
  #  name: com.serverless.${self:provider.region}.deploys # Overwrite the default deployment bucket
  #  serverSideEncryption: AES256 # when using server-side encryption
  stackTags: # Optional CF stack tags
   project: ${self:service}
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  list:
    handler: todos.list
    events:
      - http:
          path: todos
          method: get
          cors: true
  get:
    handler: todos.get
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true
  create:
    handler: todos.create
    events:
      - http:
          path: todos
          method: post
          cors: true
  update:
    handler: todos.update
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true
  delete:
    handler: todos.delete
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
